# Generated by Selenium IDE
from selenium import  webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By


class TestDemo1():
    def setup_method(self, method):
        option=Options()
        option.debugger_address='127.0.0.1:9222'
        self.driver = webdriver.Chrome(options=option)
        #隐式等待，动态的等待
        self.driver.implicitly_wait(5)

    def teardown_method(self, method):
        self.driver.quit()

    def test_demo1(self):
        #self.driver.get("https://ceshiren.com/")
        self.driver.set_window_size(994, 695)
        self.driver.find_element(By.LINK_TEXT, "所有分类").click()
        categoryele=self.driver.find_element(By.LINK_TEXT,"所有分类")
        assert'active'==categoryele.get_attribute("class")