# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium import webdriver
from selenium.webdriver.common.by import By

class TestDemo0():
    def setup_method(self, method):
        option=Options()
        option.debugger_address='127.0.0.1:9222'
        self.driver = webdriver.Chrome(options=option)
        #隐式等待，动态的等待元素，最好在实例化driver之后立刻去设置
        self.driver.implicitly_wait(5)

    def teardown_method(self, method):
        self.driver.quit()

    def test_demo0(self):
        self.driver.get("https://ceshiren.com/")
        self.driver.maximize_window()
        self.driver.find_element(By.LINK_TEXT, "所有分类").click()
        categoryele=self.driver.find_element(By.LINK_TEXT,"所有分类")
        assert 'active'==categoryele.get_attribute("class")


